variables:
   #https://registry-1.docker.io
  CI_LOCAL_REGISTRY: registry:5000
  CI_REGISTRY: registry-1.docker.io:80
  CI_DEBUG_TRACE: "true"


build:
  image: docker:stable
  stage: build
  services:
  - name: docker:stable-dind
#    entrypoint: ["dockerd-entrypoint.sh"]
#    command: ["--insecure-registry", "registry:5000"]

  before_script:
    - docker pull docker:stable
    - docker pull docker:stable-dind
    - docker image ls
    - docker image ls registry:5000/*
  
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_LOCAL_REGISTRY
    - docker tag docker:stable $CI_LOCAL_REGISTRY/docker:stable
    - docker tag docker:stable-dind $CI_LOCAL_REGISTRY/docker:stable-dind   
    - docker push $CI_LOCAL_REGISTRY/docker:stable
    - docker push $CI_LOCAL_REGISTRY/docker:stable-dind
    - docker image ls registry:5000/*
  
  after_script:
    - docker image ls
    - docker image ls registry:5000/*   

