version: '3'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes: 
      - ${PWD}/config.yml:/etc/docker/registry/config.yml
    restart: always
    container_name: registry
    
    